// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3MrI7sHhK3wfoUWLoWR5Shc02tUz0LTs',
    appId: '1:563664680147:web:9ae0eb23d4f74626915026',
    messagingSenderId: '563664680147',
    projectId: 'crud-tutorial-6daeb',
    authDomain: 'crud-tutorial-6daeb.firebaseapp.com',
    storageBucket: 'crud-tutorial-6daeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2FteC7pM2TyPgdDVOFAFQkp4mLMTKYAk',
    appId: '1:563664680147:android:e3fe224e3166399a915026',
    messagingSenderId: '563664680147',
    projectId: 'crud-tutorial-6daeb',
    storageBucket: 'crud-tutorial-6daeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TXBhcOe03cYOXYsm-aCTOimYIj7f7MQ',
    appId: '1:563664680147:ios:a11533c2ebd9fa35915026',
    messagingSenderId: '563664680147',
    projectId: 'crud-tutorial-6daeb',
    storageBucket: 'crud-tutorial-6daeb.appspot.com',
    iosBundleId: 'com.example.crudTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6TXBhcOe03cYOXYsm-aCTOimYIj7f7MQ',
    appId: '1:563664680147:ios:a11533c2ebd9fa35915026',
    messagingSenderId: '563664680147',
    projectId: 'crud-tutorial-6daeb',
    storageBucket: 'crud-tutorial-6daeb.appspot.com',
    iosBundleId: 'com.example.crudTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3MrI7sHhK3wfoUWLoWR5Shc02tUz0LTs',
    appId: '1:563664680147:web:a42eec3dc4dba091915026',
    messagingSenderId: '563664680147',
    projectId: 'crud-tutorial-6daeb',
    authDomain: 'crud-tutorial-6daeb.firebaseapp.com',
    storageBucket: 'crud-tutorial-6daeb.appspot.com',
  );
}
